#!/usr/bin/env python3
import os
import asyncio
import logging
import requests
from requests.exceptions import RequestException

# Set up logging to both file and console
log_file_path = os.path.join(os.path.dirname(__file__), 'media_cleanup_log.txt')  # Log file path in the same directory as the script
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s]: %(message)s',
    handlers=[
        logging.FileHandler(log_file_path),
        logging.StreamHandler()
    ]
)

# API configurations
READARR_API_URL = "http://192.168.50.1:8787/api/v1"
READARR_API_KEY = ""
API_TIMEOUT = 300  # 5 minutes

# Function to make API requests with error handling
async def make_api_request(url, api_key, params=None):
    try:
        headers = {'X-Api-Key': api_key}
        response = await asyncio.get_event_loop().run_in_executor(None, lambda: requests.get(url, params=params, headers=headers))
        response.raise_for_status()
        return response.json()
    except RequestException as e:
        logging.error(f'Error making API request to {url}: {e}')
        return None
    except ValueError as e:
        logging.error(f'Error parsing JSON response from {url}: {e}')
        return None

# Function to make API delete with error handling
async def make_api_delete(url, api_key, params=None):
    try:
        headers = {'X-Api-Key': api_key}
        response = await asyncio.get_event_loop().run_in_executor(None, lambda: requests.delete(url, params=params, headers=headers))
        response.raise_for_status()
        return response.json()
    except RequestException as e:
        logging.error(f'Error making API delete request to {url}: {e}')
        return None
    except ValueError as e:
        logging.error(f'Error parsing JSON response from delete request to {url}: {e}')
        return None

# Function to remove stalled Readarr downloads
async def remove_stalled_readarr_downloads():
    logging.info('Checking Readarr queue...')
    readarr_url = f'{READARR_API_URL}/queue'
    readarr_queue = await make_api_request(readarr_url, READARR_API_KEY, {'page': '1', 'pageSize': await count_records(READARR_API_URL, READARR_API_KEY)})
    if readarr_queue is not None and 'records' in readarr_queue:
        logging.info('Processing Readarr queue...')
        for item in readarr_queue['records']:
            if 'title' in item and 'status' in item and 'trackedDownloadStatus' in item:
                logging.info(f'Checking the status of {item["title"]}')
                if item['status'] == 'warning' and item['errorMessage'] == 'The download is stalled with no connections':
                    logging.info(f'Removing stalled Readarr download: {item["title"]}')
                    await make_api_delete(f'{READARR_API_URL}/queue/{item["id"]}', READARR_API_KEY, {'removeFromClient': 'true', 'blocklist': 'true'})
            else:
                logging.warning('Skipping item in Readarr queue due to missing or invalid keys')
    else:
        logging.warning('Readarr queue is None or missing "records" key')

# Make a request to view and count items in queue and return the number.
async def count_records(API_URL, API_Key):
    the_url = f'{API_URL}/queue'
    the_queue = await make_api_request(the_url, API_Key)
    if the_queue is not None and 'records' in the_queue:
        return the_queue['totalRecords']

# Main function
async def main():
    while True:
        logging.info('Running media-tools script')
        await remove_stalled_readarr_downloads()
        logging.info('Finished running media-tools script. Sleeping for 5 minutes.')
        await asyncio.sleep(API_TIMEOUT)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
