#!/usr/bin/env python3
import os
import asyncio
import logging
import requests
from requests.exceptions import RequestException
import json

# Set up logging
logging.basicConfig(
    format='%(asctime)s [%(levelname)s]: %(message)s',
    level=logging.INFO,
    handlers=[logging.StreamHandler()]
)

# Whisparr API endpoint
WHISPARR_API_URL = (os.environ['WHISPARR_URL']) + "/api/v1"
WHISPARR_API_KEY = os.environ['WHISPARR_API_KEY']

# API timeout for API requests in seconds
API_TIMEOUT = int(os.environ['API_TIMEOUT'])  # 10 minutes

# Function to make API requests with error handling
async def make_api_request(url, api_key, params=None):
    try:
        headers = {'X-Api-Key': api_key}
        response = await asyncio.get_event_loop().run_in_executor(None, lambda: requests.get(url, params=params, headers=headers))
        response.raise_for_status()
        return response.json()
    except RequestException as e:
        logging.error(f'Error making API request to {url}: {e}')
        return None
    except ValueError as e:
        logging.error(f'Error parsing JSON response from {url}: {e}')
        return None

# Function to make API delete with error handling
async def make_api_delete(url, api_key, params=None):
    try:
        headers = {'X-Api-Key': api_key}
        response = await asyncio.get_event_loop().run_in_executor(None, lambda: requests.delete(url, params=params, headers=headers))
        response.raise_for_status()
        return response.json()
    except RequestException as e:
        logging.error(f'Error making API request to {url}: {e}')
        return None
    except ValueError as e:
        logging.error(f'Error parsing JSON response from {url}: {e}')
        return None

# Function to remove stalled Whisparr downloads
async def remove_stalled_whisparr_downloads():
    logging.info('Checking Whisparr queue...')
    whisparr_url = f'{WHISPARR_API_URL}/queue'
    whisparr_queue = await make_api_request(whisparr_url, WHISPARR_API_KEY, {'page': '1', 'pageSize': await count_records(WHISPARR_API_URL, WHISPARR_API_KEY)})
    if whisparr_queue is not None and 'records' in whisparr_queue:
        logging.info('Processing Whisparr queue...')
        for item in whisparr_queue['records']:
            if 'title' in item and 'status' in item and 'trackedDownloadStatus' in item:
                logging.info(f'Checking the status of {item["title"]}')
                if item['status'] == 'warning' and item['errorMessage'] == 'The download is stalled with no connections':
                    logging.info(f'Removing stalled Whisparr download: {item["title"]}')
                    await make_api_delete(f'{WHISPARR_API_URL}/queue/{item["id"]}', WHISPARR_API_KEY, {'removeFromClient': 'true', 'blocklist': 'true'})
                else:
                    logging.warning('Skipping item in Whisparr queue due to missing or invalid keys')
    else:
        logging.warning('Whisparr queue is None or missing "records" key')

# Make a request to view and count items in queue and return the number.
async def count_records(API_URL, API_Key):
    the_url = f'{API_URL}/queue'
    the_queue = await make_api_request(the_url, API_Key)
    if the_queue is not None and 'records' in the_queue:
        return the_queue['totalRecords']

# Main function
async def main():
    while True:
        logging.info('Running media-tools script')
        await remove_stalled_whisparr_downloads()
        logging.info('Finished running media-tools script. Sleeping for 10 minutes.')
        await asyncio.sleep(API_TIMEOUT)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
